apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-producer
  template:
    metadata:
      labels:
        app: notification-producer
    spec:
      containers:
        - name: app
          image: notificationpoc.azurecr.io/notification-producer:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always